apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: spinnaker-stage
  namespace: nginx-for-spinnaker
  annotations:
    moniker.spinnaker.io/stack: staging
spec:
  selector:
    matchLabels:
      app: spinnaker
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: spinnaker
    spec:
      containers:
      - name: spinnaker
        image: hello-world
        ports:
        - containerPort: 80
        
---

kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  namespace: nginx-for-spinnaker
spec:
  selector:
    app: spinnaker
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
